name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        viewport:
          - "375x667"
          - "768x1024"
          - "1280x720"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests with Viewport
      run: |
        VIEWPORT_WIDTH=$(echo "${{ matrix.viewport }}" | cut -d 'x' -f 1)
        VIEWPORT_HEIGHT=$(echo "${{ matrix.viewport }}" | cut -d 'x' -f 2)

        npx cypress run --spec cypress/e2e/tests/lumaAssessment.cy.js \
          --browser chrome \
          --env viewportWidth=$VIEWPORT_WIDTH,viewportHeight=$VIEWPORT_HEIGHT \
          --reporter cypress-mochawesome-reporter \
          --reporter-options reportDir=cypress/reports/${{ matrix.viewport }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-reports-${{ matrix.viewport }}
        path: cypress/reports/${{ matrix.viewport }}

    - name: Publish Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/reports