name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        viewport:
          - width: 375
            height: 667
          - width: 768
            height: 1024
          - width: 1280
            height: 720

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests with Viewport
      run: |
        mkdir -p cypress/reports/${{ matrix.viewport.width }}x${{ matrix.viewport.height }}
        npx cypress run --spec cypress/e2e/tests/lumaAssessment.cy.js \
          --browser chrome \
          --env viewportWidth=${{ matrix.viewport.width }},viewportHeight=${{ matrix.viewport.height }} \
          --reporter cypress-mochawesome-reporter \
          --reporter-options reportDir=cypress/reports/${{ matrix.viewport.width }}x${{ matrix.viewport.height }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-reports-${{ matrix.viewport.width }}x${{ matrix.viewport.height }}
        path: cypress/reports/${{ matrix.viewport.width }}x${{ matrix.viewport.height }}

  publish-reports:
    runs-on: ubuntu-latest
    needs: cypress-tests  # Aguarda a conclusão dos jobs acima

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download all test artifacts
      uses: actions/download-artifact@v3
      with:
        name: cypress-reports-375x667
        path: cypress/reports/375x667

    - uses: actions/download-artifact@v3
      with:
        name: cypress-reports-768x1024
        path: cypress/reports/768x1024

    - uses: actions/download-artifact@v3
      with:
        name: cypress-reports-1280x720
        path: cypress/reports/1280x720

    - name: Publish Combined Reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/reports
        keep_files: true
    
    - name: Generate Report Links
      run: |
        echo "### Cypress Test Reports" > summary.md
        echo "- [1280x720 Report](https://tonymich19.github.io/luma-assessment/1280x720/index.html)" >> summary.md
        echo "- [768x1024 Report](https://tonymich19.github.io/luma-assessment/768x1024/index.html)" >> summary.md
        echo "- [375x667 Report](https://tonymich19.github.io/luma-assessment/375x667/index.html)" >> summary.md
        cat summary.md
