name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        viewport:
          - width: 375
            height: 667
          - width: 768
            height: 1024
          - width: 1280
            height: 720

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests with Viewport
      run: |
        mkdir -p cypress/reports/${{ matrix.viewport.width }}x${{ matrix.viewport.height }}
        npx cypress run --spec cypress/e2e/tests/lumaAssessment.cy.js \
          --browser chrome \
          --env viewportWidth=${{ matrix.viewport.width }},viewportHeight=${{ matrix.viewport.height }} \
          --reporter cypress-mochawesome-reporter \
          --reporter-options reportDir=cypress/reports/${{ matrix.viewport.width }}x${{ matrix.viewport.height }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-reports-${{ matrix.viewport.width }}x${{ matrix.viewport.height }}
        path: cypress/reports/${{ matrix.viewport.width }}x${{ matrix.viewport.height }}

    - name: Publish Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/reports
        keep_files: true
